feat(PN-9571): adaptation of drag and drop component to WCAG 2.2 standards
pagopa/mui-italia pull request #485
Opened 2024-04-08 13:57 UTC by SarahDonvito

## Short description
Added CTA in _SingleFileInput_ component

### Preview
![image](https://github.com/pagopa/mui-italia/assets/73442810/016b97c3-e4ac-4485-9e0b-2b45e9aecfdc)

## List of changes proposed in this pull request
- Added button to component to make CTA more accessible
- Added prop for copy of button

## Product
Piattaforma Notifiche -> SEND

## How to test
Run storybook and go to SingleFileInput component to check that box has button to upload file

2024-04-09 09:21 UTC, ZorbaDimatteo requested changes
@SarahDonvito Error case scenario doesn't seem to be managed correctly
![Screenshot 2024-04-09 at 11 19 31](https://github.com/pagopa/mui-italia/assets/18332250/7f3ad7a4-2593-4ca8-9dd2-93945c8d02b6)

2024-04-09 15:19 UTC, ZorbaDimatteo requested changes

2024-04-09 15:19 UTC, ZorbaDimatteo commented on src/components/SingleFileInput/SingleFileInput.tsx
> +  /** The button to be displayed in the dropzone. */
@SarahDonvito Try to explain better this prop: is not the button per se (which is basically always included) but the label for the button

2024-04-09 15:19 UTC, ZorbaDimatteo commented on src/components/SingleFileInput/SingleFileInput.tsx
> +                  <Button sx={{ margin: "0 10px" }} variant="contained">
@SarahDonvito this two block of code (STATUS.IDLE and STATUS.ERROR) are almost identical, except for `color` prop.
Try to improve code readability and reusability

2024-04-10 14:28 UTC, ZorbaDimatteo approved these changes

2024-04-10 14:29 UTC, ZorbaDimatteo commented
@Carminepo2 @ruggerocastagnola Can you check this PR too?

2024-04-11 07:49 UTC, Carminepo2 commented
LGTM 👍

2024-04-12 12:33 UTC, merged